### ISSUE TITLE
Automatic cycle (by port number)

### ISSUE THREAD

**Issue by lapidavishai** [eranws/KinectRelay#10]
<h3>cycle-1<h3>

[6 on]
4 (0.5 on 0.2 off) ,4 (0.5 on 0.2 off),4 (0.5 on 0.2 off),7 (2 on)
4 (0.5 on 0.2 off) ,4 (0.5 on 0.2 off),4 (0.5 on 0.2 off),7 (2 on)
4 (0.5 on 0.2 off) ,4 (0.5 on 0.2 off),4 (0.5 on 0.2 off),7 (2 on)
[6 off]

2 (0.2 on 0.2 off) ,4 (1 on), 2 (0.2 on 0.2 off) ,4 (1 on), 2 (0.2 on 0.2 off) ,4 (1 on), 2 (0.2 on 0.2 off) ,4 (1 on),

2 (0.2 on 0.2 off) , 2 (0.2 on 0.2 off) , 2 (0.2 on 0.2 off) , 2 (0.2 on 0.2 off) ,2 (0.2 on 0.2 off) ,
3 (3 on)

4 (0.5 on 0.2 off) ,4 (0.5 on 0.2 off),4 (0.5 on 0.2 off),7 (2 on)
4 (0.5 on 0.2 off) ,4 (0.5 on 0.2 off),4 (0.5 on 0.2 off),7 (2 on)
4 (0.5 on 0.2 off) ,4 (0.5 on 0.2 off),4 (0.5 on 0.2 off),7 (2 on)

2 (0.2 on 0.2 off) ,4 (1 on), 2 (0.2 on 0.2 off) ,4 (1 on), 2 (0.2 on 0.2 off) ,4 (1 on), 2 (0.2 on 0.2 off) ,4 (1 on),

//loop until 2.5 min reach
//end of cycle- hold for 2.5 min without nothing (voiceover in room background)

<h3>cycle-2<h3>

5 (5 on)
2 (0.2 on, 0.7 off), 2 (0.2 on, 0.7 off), 2 (1 on)

4 ( 0.3 on), 2 (0.3 on), 8 (0.3 on),  7 ( 1.5 on)
4 ( 0.3 on), 2 (0.3 on), 8 (0.3 on),  7 ( 1.5 on)
4 ( 0.3 on), 2 (0.3 on), 8 (0.3 on),  7 ( 1.5 on)
4 ( 0.3 on), 2 (0.3 on), 8 (0.3 on),  7 ( 1.5 on)
3 ( 1 on), 2 (0.2 on, 0.7 off), 2 (0.2 on, 0.7 off), 2 (1 on)

//loop until 2.5 min reach
//end of cycle- hold for 2.5 min without nothing (voiceover in room background)

<h3>cycle-3<h3>

6 (3 on 2 off), 6 (3 on 2 off), 6 (3 on 2 off),

5 [on]
8 (0.3 on 0.2 off), 8 (0.3 on 0.2 off), 8 (0.3 on 0.2 off) ,8 (0.3 on 0.2 off), 8 (0.3 on 0.2 off)
8 (0.3 on 0.2 off), 8 (0.3 on 0.2 off), 8 (0.3 on 0.2 off) ,8 (0.3 on 0.2 off), 8 (0.3 on 0.2 off)
8 (0.3 on 0.2 off), 8 (0.3 on 0.2 off), 8 (0.3 on 0.2 off) ,8 (0.3 on 0.2 off), 8 (0.3 on 0.2 off)
5[off]

7 (3 on)

2 ( 1 on), 4 (1 on), 3 (3 on)

//loop until 2.5 min reach
//end of cycle- hold for 2.5 min without nothing (voiceover in room background)

**Comment by eranws** [comment]
Done.
can you write (or upload an image) of which number goes to which pin?

**Comment by eranws** [comment]
btw, i thinks it would be better to use shorter patterns with more repetitions...

**Comment by lapidavishai** [comment]
![photo on 2015-06-29 at 01 26](https://cloud.githubusercontent.com/assets/12587383/8398634/7a7b510a-1dff-11e5-9dbe-1919666db37f.jpg)

**Comment by lapidavishai** [comment]
so cut them in the middle
