### ISSUE TITLE
Normally Closed

### ISSUE THREAD

**Issue by lapidavishai** [eranws/KinectRelay#12]
all the pins are HIGH all the time, when triggered from sensor they are LOW.
we need it to work the opposite way.

i think there is one more step to check, and if its still not working then to bring it back to how it was

Thanx a LOT my man

**Comment by eranws** [comment]
I changed it already... - did you pull from master?

## 

Eran Weissenstern

**Comment by lapidavishai** [comment]
i re-downloaded the zip file of  KinectRelay and opened the KinectRelay.pde.it didn't work like it used to be so i assumed its the new&updated file
it used to start all the appliances at once,  and then after a few seconds to shut them all off and start working properly.now it turning them all on and just stay like it, when its triggers from sensor its shutting them down by the beat. when finished its stays on again.
maybe i should download a different file from github?
want  to skype maybe today?

Avishai

Date: Mon, 9 May 2016 18:13:04 -0700

**Comment by eranws** [comment]
Firmata starts where all pins are LOW.
possible solution is to create an alternative firmata, and set all pins to HIGH at startup:
https://github.com/firmata/arduino/blob/master/examples/StandardFirmata/StandardFirmata.ino#L695

**Comment by eranws** [comment]
actually here:
https://github.com/firmata/arduino/blob/master/examples/StandardFirmata/StandardFirmata.ino#L292

**Comment by eranws** [comment]
solution here: (digital pins set to HIGH at startup)
https://github.com/eranws/arduino/blob/master/examples/StandardFirmata/StandardFirmata.ino
