### ISSUE TITLE
dynamic gestures

### ISSUE THREAD

**Issue by eranws** [eranws/KinectRelay#4]
- [x] single hand circles
- [x] two hands going up
- [x] full body twist

**Comment by eranws** [comment]
Circles - Done!

![screenshot 2015-06-01 01 13 25](https://cloud.githubusercontent.com/assets/770012/7904213/a6144b24-07fb-11e5-9887-81d785285119.png)

**Comment by lapidavishai** [comment]
yayyy

such a king you are!
