### ISSUE TITLE
patterns, pulses, etc.

### ISSUE THREAD

**Issue by eranws** [eranws/KinectRelay#5]

**Comment by lapidavishai** [comment]
by order of actions..

Blender: 

A- 1.75s on, (all others ports off)
B- pulses= 0.5 on, 0.5 off, 0.5 on, 0.5 off. 1 on, 0.5 off    *4 times
C-Z- same

Vacuum cleaner: 

A- Z- pulses= 0.5 on, 0.5 off, 0.5 on, 0.5 off, 1.5 on, 0.5 off         *3 times

Fan:  

A-Z- pulses= 4s on, 2 off   \* 6 times

Electric razor:

A- 0.12 on, 0.12 off, 0.12 on, 0.12 off, 0.12 on, 0.12 off, 0.12 on, 0.12 off   *2 times (all  others ports off)
B-Z- 0.12 on, 0.12 off, 0.12 on, 0.12 off, 0.12 on, 0.12 off, 0.12 on, 0.12 off, 1 on, 0.5 off

Radio:

A-Z- pulses= 0.5 on, 0.5 off, 2 on, 1 off  \* 2 times

Hand Mixer (drill):

A-Z- pulses= 0.75 on, 0.25 off, 0.12 on, 0.12 off, 0.12 on, 0.12 off.  *4 times

Hair Dryer:

A-Z- pulses= 3s on, 1s off   *4 times

hope its fine..
