### ISSUE TITLE
What to do when two people in the spot?

### ISSUE THREAD

**Issue by eranws** [eranws/KinectRelay#7]
stop?
give error message(sound?)

**Comment by lapidavishai** [comment]
im going to make it in the size of one person,
but maybe when two pepole on spot= turn of port number-8 ( the projector of the conductor stage)

**Comment by eranws** [comment]
maybe also make a movie with an angry conductor doing (no no no)...

**Comment by lapidavishai** [comment]
it would be a nice idea, ill make one
